# -*- coding: utf-8 -*-
"""Mat_Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpkxRHw1gpUzCgXji3YJbL2ITsf6bqEQ
"""

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Material/train1.csv"

import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import pickle
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

df = pd.read_csv(path)
df = pd.DataFrame(df)
df

# df1 = df.drop(columns=['Array','flexural_str'])
# df1

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

df_encoded = encoder.fit_transform(df[['orientation','infill_pattern']])

print(df_encoded.shape)

odf = pd.DataFrame.sparse.from_spmatrix(df_encoded)
odf

idf = df[['layer_thick',	'infill_density',	'mwcnt',	'graphene',	'tensile_str']]
idf

cdf = pd.concat([odf, idf], axis=1)
cdf

cdf.columns = cdf.columns.astype(str)
cdf

scaler = StandardScaler()
scaler.fit(cdf)


# Fit and transform the data
scaled_data_dff = scaler.transform(cdf)

# Create a new DataFrame with the scaled data
dfn = pd.DataFrame(scaled_data_dff, columns=cdf.columns)


print("\nNormalized DataFrame (using StandardScaler):")
dfn

# Initialize StandardScaler

scaler_y = StandardScaler()

# Fit and transform the target variable
scaler_y.fit(cdf[['tensile_str']])

hehe = scaler_y.transform(cdf[['tensile_str']])

dfn

X = dfn.drop(columns=['tensile_str'])
y = dfn['tensile_str']

from sklearn.model_selection import train_test_split

# # Assuming df is your DataFrame and 'target_column' is your target variable
# y = cdf['target_column']  # Target variable
# X = cdf.drop(columns=['target_column'])  # Features


# Split the data into training and temp (validation + testing) sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=24)

# Split the temp set into validation and testing sets
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=48)

# Print the shapes to verify the split
print("Training data shape:", X_train.shape, y_train.shape)
print("Validation data shape:", X_val.shape, y_val.shape)
print("Testing data shape:", X_test.shape, y_test.shape)

#Hyperparameter tuning XGboost

n_estimators = [100, 500, 1000]
learning_rate = [0.05, 0.1, 0.15, 0.2]
max_depth = [2, 3, 4]     #[2, 3, 5, 6, 7]
booster = ['gbtree']
min_child_weight = [1,2,3,4,5]
base_score = [0.25,0.5,0.75,1]
early_stopping_rounds = [10, 50, 100]

hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score,
    'early_stopping_rounds': early_stopping_rounds
    }

import xgboost as xgb

XGreg = xgb.XGBRegressor(objective='reg:squarederror')

from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import make_regression
# 4 fold
random_cv = RandomizedSearchCV(estimator=XGreg,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',
            verbose = 5,
            return_train_score = True,
            random_state=42,
            )

random_cv.fit(X_train,y_train,eval_set=[(X_val, y_val)])

bes_reg = random_cv.best_estimator_
bes_reg

bes_reg.fit(X_train,y_train,eval_set=[(X_val, y_val)])

y_pred_test = bes_reg.predict(X_test)
y_pred_val = bes_reg.predict(X_val)
y_pred_train = bes_reg.predict(X_train)

mse = mean_absolute_error(y_test, y_pred_test)
print(f'Mean Absolute Error: {mse}')

mse = mean_absolute_error(y_val, y_pred_val)
print(f'Mean absolute Error: {mse}')

mse = mean_absolute_error(y_train, y_pred_train)
print(f'Mean absolute Error: {mse}')

y_pred_test = pd.DataFrame(y_pred_test)
y_pred_test.columns = ['Label']

y_test = pd.DataFrame(y_test)
y_test.columns = ['Label']

y_pred_val = pd.DataFrame(y_pred_val)
y_pred_val.columns = ['Label']

y_pred_train = pd.DataFrame(y_pred_train)
y_pred_train.columns = ['Label']

y_train = pd.DataFrame(y_train)
y_train.columns = ['Label']

y_val = pd.DataFrame(y_val)
y_val.columns = ['Label']

y_pred_large_test = scaler_y.inverse_transform(y_pred_test)
y_pred_large_test

y_pred_large_train = scaler_y.inverse_transform(y_pred_train)
y_pred_large_train

y_pred_large_val = scaler_y.inverse_transform(y_pred_val)
y_pred_large_val

y_large_train = scaler_y.inverse_transform(y_train)
y_large_train

y_large_val = scaler_y.inverse_transform(y_val)
y_large_val

y_large_test = scaler_y.inverse_transform(y_test)
y_large_test

lmse_test = mean_absolute_error(y_large_test, y_pred_large_test)
print(f'Mean abs Error: {lmse_test}')

lmse_val = mean_absolute_error(y_large_val, y_pred_large_val)
print(f'Mean abs Error: {lmse_val}')

lmse_train = mean_absolute_error(y_large_train, y_pred_large_train)
print(f'Mean abs Error: {lmse_train}')

mean = df['tensile_str'].mean()
mean

with open('/content/drive/MyDrive/Material/Models/Tens_orientation.pkl', 'wb') as file:
    pickle.dump(bes_reg, file)

# Save preprocessors so the prediction app uses the exact same objects
with open('/content/drive/MyDrive/Material/Models/Tens_encoder.pkl', 'wb') as file:
    pickle.dump(encoder, file)
with open('/content/drive/MyDrive/Material/Models/Tens_scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)
with open('/content/drive/MyDrive/Material/Models/Tens_scaler_y.pkl', 'wb') as file:
    pickle.dump(scaler_y, file)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Reconstruct a test DataFrame that contains the original categorical variables.
# Use the indices from X_test to select the corresponding rows in the original DataFrame.
test_original = df.loc[X_test.index].copy()

# Add the predictions and actual tensile strength (in original scale) to the DataFrame.
test_original["Predicted tensile_str"] = y_pred_large_test.flatten()
test_original["Actual tensile_str"] = y_large_test.flatten()

# ----- Option 1: FacetGrid Scatter Plots -----
# This creates a grid of scatter plots for each unique combination of orientation and infill_pattern.
g = sns.FacetGrid(test_original, row="orientation", col="infill_pattern", height=3, aspect=1.5)
g.map_dataframe(sns.scatterplot, x="Actual tensile_str", y="Predicted tensile_str", color='b')
g.set_axis_labels("Actual Tensile Strength", "Predicted Tensile Strength")
g.fig.suptitle("Model Predictions vs Actual Tensile Strength by Combination", y=1.03)
plt.show()

# ----- Option 2: Grouped Bar Plot -----
# Group the test data by the two categorical features and calculate the mean actual and predicted tensile strength.
grouped = test_original.groupby(["orientation", "infill_pattern"])[["Actual tensile_str", "Predicted tensile_str"]].mean().reset_index()

# Melt the grouped DataFrame to long format for easier plotting with seaborn.
grouped_melted = pd.melt(grouped, id_vars=["orientation", "infill_pattern"],
                           value_vars=["Actual tensile_str", "Predicted tensile_str"],
                           var_name="Type", value_name="Tensile Strength")

plt.figure(figsize=(10, 6))
sns.barplot(data=grouped_melted, x="orientation", y="Tensile Strength", hue="infill_pattern", ci=None)
plt.title("Mean Actual vs Predicted Tensile Strength by Orientation and Infill Pattern")
plt.xlabel("Orientation")
plt.ylabel("Tensile Strength")
plt.legend(title="Infill Pattern")
plt.show()

# Define the graphene levels you are interested in.
graphene_levels = [0, 0.5, 1, 1.5]

# Now filter the DataFrame for the desired graphene values.
df_graphene = df[df['graphene'].isin(graphene_levels)]


import matplotlib.pyplot as plt
import seaborn as sns

# Filter the DataFrame for the desired graphene values.
df_graphene = df[df['graphene'].isin(graphene_levels)]

# Create a FacetGrid to plot separate boxplots for each combination of "orientation" and "infill_pattern".
g = sns.FacetGrid(df_graphene, col="orientation", row="infill_pattern", margin_titles=True, height=3)
g.map_dataframe(sns.boxplot, x="graphene", y="tensile_str", order=graphene_levels)
g.set_axis_labels("Graphene Level", "Tensile Strength")
g.fig.subplots_adjust(top=0.9)
g.fig.suptitle("Tensile Strength by Graphene Level Under Different Conditions")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Define the graphene levels you are interested in.
graphene_levels = [0, 0.5, 1, 1.5]

# Filter the DataFrame for the selected graphene values.
df_graphene = df[df['graphene'].isin(graphene_levels)]

plt.figure(figsize=(8, 6))
sns.boxplot(data=df_graphene, x='graphene', y='tensile_str', order=graphene_levels)
plt.title("Tensile Strength Distribution at Selected Graphene Levels")
plt.xlabel("Graphene Level")
plt.ylabel("Tensile Strength")
plt.show()

# Define the graphene levels you are interested in.
graphene_levels = [0, 0.5, 1, 1.5]

# Filter the DataFrame for the desired graphene values and ensure MWCNT is 0
df_graphene = df[(df['graphene'].isin(graphene_levels)) & (df['mwcnt'] == 0)]

import matplotlib.pyplot as plt
import seaborn as sns

# Create a FacetGrid to plot separate boxplots for each combination of "orientation" and "infill_pattern".
g = sns.FacetGrid(df_graphene, col="orientation", row="infill_pattern", margin_titles=True, height=3)
g.map_dataframe(sns.boxplot, x="graphene", y="tensile_str", order=graphene_levels)
g.set_axis_labels("Graphene Level", "Tensile Strength")
g.fig.subplots_adjust(top=0.9)
g.fig.suptitle("Tensile Strength by Graphene Level Under Different Conditions (MWCNT = 0)")
plt.show()

################################################################################################################################################

##########################################################################################

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder1 = OneHotEncoder()

df_encoded1 = encoder1.fit_transform(df[['orientation','infill_pattern']])

print(df_encoded1.shape)

odf1 = pd.DataFrame.sparse.from_spmatrix(df_encoded1)
odf1

idf1 = df[['layer_thick',	'infill_density',	'mwcnt',	'graphene',	'flexural_str']]
idf1

cdf1 = pd.concat([odf1, idf1], axis=1)
cdf1

cdf1.columns = cdf1.columns.astype(str)
cdf1

scaler1 = StandardScaler()
scaler1.fit(cdf1)


# Fit and transform the data
scaled_data_dff1 = scaler1.transform(cdf1)

# Create a new DataFrame with the scaled data
dfn1 = pd.DataFrame(scaled_data_dff1, columns=cdf1.columns)


print("\nNormalized DataFrame (using StandardScaler):")
dfn1

# Initialize StandardScaler

scaler_y1 = StandardScaler()

# Fit and transform the target variable
scaler_y1.fit(cdf1[['flexural_str']])

hehe1 = scaler_y1.transform(cdf1[['flexural_str']])

dfn1

X1 = dfn1.drop(columns=['flexural_str'])
y1 = dfn1['flexural_str']

from sklearn.model_selection import train_test_split

# # Assuming df is your DataFrame and 'target_column' is your target variable
# y = cdf['target_column']  # Target variable
# X = cdf.drop(columns=['target_column'])  # Features


# Split the data into training and temp (validation + testing) sets
X_train1, X_temp1, y_train1, y_temp1 = train_test_split(X1, y1, test_size=0.2, random_state=24)

# Split the temp set into validation and testing sets
X_val1, X_test1, y_val1, y_test1 = train_test_split(X_temp1, y_temp1, test_size=0.5, random_state=48)

# Print the shapes to verify the split
print("Training data shape:", X_train1.shape, y_train1.shape)
print("Validation data shape:", X_val1.shape, y_val1.shape)
print("Testing data shape:", X_test1.shape, y_test1.shape)

#Hyperparameter tuning XGboost

n_estimators = [100, 500, 1000]
learning_rate = [0.05, 0.1, 0.15, 0.2]
max_depth = [2, 3, 4, 7]     #[2, 3, 5, 6, 7]
booster = ['gbtree']
min_child_weight = [1,2,3,4,5]
base_score = [0.25,0.5,0.75,1]
early_stopping_rounds = [10, 50, 100]

hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score,
    'early_stopping_rounds': early_stopping_rounds
    }

import xgboost as xgb

XGreg1 = xgb.XGBRegressor(objective='reg:squarederror')

from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import make_regression
# 4 fold
random_cv1 = RandomizedSearchCV(estimator=XGreg1,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',
            verbose = 5,
            return_train_score = True,
            random_state=42,
            )

random_cv1.fit(X_train1,y_train1,eval_set=[(X_val1, y_val1)])

bes_reg1 = random_cv1.best_estimator_
bes_reg1

bes_reg1.fit(X_train1,y_train1,eval_set=[(X_val1, y_val1)])

y_pred_test1 = bes_reg1.predict(X_test1)
y_pred_val1 = bes_reg1.predict(X_val1)
y_pred_train1 = bes_reg1.predict(X_train1)

mse = mean_absolute_error(y_test1, y_pred_test1)
print(f'Mean Absolute Error: {mse}')

mse = mean_absolute_error(y_val1, y_pred_val1)
print(f'Mean absolute Error: {mse}')

mse = mean_absolute_error(y_train1, y_pred_train1)
print(f'Mean absolute Error: {mse}')

y_pred_test1 = pd.DataFrame(y_pred_test1)
y_pred_test1.columns = ['Label']

y_test1 = pd.DataFrame(y_test1)
y_test1.columns = ['Label']

y_pred_val1 = pd.DataFrame(y_pred_val1)
y_pred_val1.columns = ['Label']

y_pred_train1 = pd.DataFrame(y_pred_train1)
y_pred_train1.columns = ['Label']

y_train1 = pd.DataFrame(y_train1)
y_train1.columns = ['Label']

y_val1 = pd.DataFrame(y_val1)
y_val1.columns = ['Label']

y_pred_large_test1 = scaler_y1.inverse_transform(y_pred_test1)
y_pred_large_test1

y_pred_large_train1 = scaler_y1.inverse_transform(y_pred_train1)
y_pred_large_train1

y_pred_large_val1 = scaler_y1.inverse_transform(y_pred_val1)
y_pred_large_val1

y_large_train1 = scaler_y1.inverse_transform(y_train1)
y_large_train1

y_large_val1 = scaler_y1.inverse_transform(y_val1)
y_large_val1

y_large_test1 = scaler_y1.inverse_transform(y_test1)
y_large_test1

lmse_test = mean_absolute_error(y_large_test1, y_pred_large_test1)
print(f'Mean abs Error: {lmse_test}')

lmse_val = mean_absolute_error(y_large_val1, y_pred_large_val1)
print(f'Mean abs Error: {lmse_val}')

lmse_train = mean_absolute_error(y_large_train1, y_pred_large_train1)
print(f'Mean abs Error: {lmse_train}')

mean = df['flexural_str'].mean()
mean

with open('/content/drive/MyDrive/Material/Models/Flex_orientation.pkl', 'wb') as file:
    pickle.dump(bes_reg1, file)

# Save preprocessors so the prediction app uses the exact same objects
with open('/content/drive/MyDrive/Material/Models/Flex_encoder.pkl', 'wb') as file:
    pickle.dump(encoder1, file)
with open('/content/drive/MyDrive/Material/Models/Flex_scaler.pkl', 'wb') as file:
    pickle.dump(scaler1, file)
with open('/content/drive/MyDrive/Material/Models/Flex_scaler_y.pkl', 'wb') as file:
    pickle.dump(scaler_y1, file)